# Working with Matrices and Vectors in Python

This is one area where Python is a  bit awkward. Matrices are by default *numpy-arrays*. Here I should mention that Python has the datatype *matrix*; but this datatype is clumsy, and using it you typically run into compatability problems with function which take only *array* arguments.

In [7]:
# Always start with the import of the main packages
import numpy as np
import matplotlib.pyplot as plt

## Matrices 

In [8]:
myMatrix = np.array([[1,2],
            [3,4]])
print(f'{myMatrix}\n and the transpose is \n {myMatrix.T}')

[[1 2]
 [3 4]]
 and the transpose is 
 [[1 3]
 [2 4]]


### Scalar product

Using the commands *hstack* and *vstack* you can generate matrices, from vectors and/or other matrices:

In [9]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,1],[2,2]])
print(f'{A} * {B} = {A @ B}')

[[1 2]
 [3 4]] * [[1 1]
 [2 2]] = [[ 5  5]
 [11 11]]


## Vectors

The quickest way to create a row and a column vector, respectively, is

In [4]:
row_vector = np.r_[0:10:2]
print(row_vector)

col_vector = np.c_[0:10:3]
print(col_vector)

[0 2 4 6 8]
[[0]
 [3]
 [6]
 [9]]


### Row-vectors

To create a row-vector, you can use different constructs:

In [12]:
def showMe(txt, data):
    print(f'{txt}: {data} has the shape {data.shape}')

x = np.array([1,3])
showMe('x', x)

x2d = np.atleast_2d(x)
showMe('x2d', x2d)

# or
x_rowVector = x[np.newaxis]
showMe('x_rowVector: ', x_rowVector)

# or
x_rowVector = x.reshape((1,2))

x: [1 3] has the shape (2,)
x2d: [[1 3]] has the shape (1, 2)
x_rowVector: : [[1 3]] has the shape (1, 2)


### Column-vectors

To create a column vector, use <code>np.column_stack</code>

In [14]:
x = np.arange(5)
y = x**2
np.column_stack((x, y))

array([[ 0,  0],
       [ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

Alternative ways to generate column-vectors:

In [6]:
x_colVector = x[:,np.newaxis]
showMe('x_colVector: ', x_colVector)

# or
x_colVector = x.reshape(len(x),1)
showMe('x_colVector: ', x_colVector)

# or
x_colVector = np.c_[x]
showMe('x_colVector: ', x_colVector)

x_colVector: : [[1]
 [3]] has the shape (2, 1)
x_colVector: : [[1]
 [3]] has the shape (2, 1)
x_colVector: : [[1]
 [3]] has the shape (2, 1)


## Lists vs Arrays
Watch the difference between a Python *List*, which is NOT a numpy structure, and a 1-d array:

In [17]:
my_list = [1, 2]
# In the next line, I "catch an error" so that the code still works
try:
    print(my_list + 2)
except TypeError:
    print('I cannot add a number to a list')

my_vector = np.array(my_list)
print(my_vector + 2)


I cannot add a number to a list
[3 4]


### Vector product

In [19]:
v1 = np.array([1,2,3])
v2 = np.array([1,1,1])
print(np.cross(v1,v2))

[-1  2 -1]


## Zeros, Ones, and NaNs

Python is not as 2d-matrix oriented as Matlab. For example, with one element for the command <code>np.zeros</code> or <code>ones</code> you produce a vector, not a 2d-matrix:

In [20]:
np.zeros(3)

array([0., 0., 0.])

Also very helpful: <code>np.zeros_like</code> and <code>np.ones_like</code>

In [21]:
np.zeros_like(v1)

array([0, 0, 0])

In [22]:
np.ones_like(v1)

array([1, 1, 1])

When generating 2d matrices, watch out that the size has to be specified as *tuple* **within** the brackets

In [10]:
np.ones( (3,2) )

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Matrices with *nans* have to be generated with a small trick:

In [11]:
np.nan * np.ones( (3,2) )

array([[nan, nan],
       [nan, nan],
       [nan, nan]])

## Broadcasting

Under certain condisions, Python is pretty good at *expanding* your input to match a corresponding array. The simplest case is when you add a scalar to a matrix:

In [12]:
A = np.reshape(np.arange(6), (3,2))
print(A)
A+10

[[0 1]
 [2 3]
 [4 5]]


array([[10, 11],
       [12, 13],
       [14, 15]])

In many cases Python finds the correct shape also for more complex pairs of matrices. This runs under [broadcasting](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html). The important point is that the number of the last dimension of the first array (here "A") has to match one of the dimension of the following array:

In [13]:
print(A.shape)
A + np.array([10,20])

(3, 2)


array([[10, 21],
       [12, 23],
       [14, 25]])